### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by farahshamout** [dlchao/corvid#3]
Hello,

Thank you for sharing your code.

How much time does 'run-cdc-2020-03-13.sh' take to run? I am running four scripts (one for each setting) and I have a 48 hour time limit per job on the cluster, so I want to check if it's below 48 hours..

**Comment by dlchao** [comment]
I think run-cdc-2020-03-13.sh finishes overnight using one core on my laptop. Each corvid run in that set takes about 15 minutes, and that bash script just runs jobs one at a time so it would run on any system.

**Comment by farahshamout** [comment]
Great thanks. The first corvid runs just completed and they each took ~ 10 hours.
